[tool.isort]
profile = "black"
multi_line_output = 3
known_first_party = [
    "jupyterlite",
]

[tool.jupyter-releaser]
skip = ["build-npm", "build-python", "check-links", "check-manifest"]

[tool.jupyter-releaser.hooks]
after-build-changelog = ["yarn lint", "yarn lint check"]
before-check-npm = ["doit dist"]

[tool.jupyter-releaser.options]
version-cmd = "doit version:bump"
