name: Windows Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  win-dev:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C CALL {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python and mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: .binder/environment.yml
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Build
        run: doit build
      - name: Dist
        run: doit dist
      - name: Lint
        run: doit lint
      - name: Lint
        run: doit dev
